# Core site labels
site:
  - changed-files:
    - any-glob-to-any-file: ['docs/**/*.md', 'docs/*.md']
    - all-globs-to-any-file: ['!docs/blog/**', '!docs/licenses/**']  # Exclude blog and licenses

blog:
  - changed-files:
    - any-glob-to-any-file: ['docs/blog/*', 'docs/blog/*/*', 'docs/blog/*/*/*']

licenses:
  - changed-files:
    - any-glob-to-any-file: ['docs/licenses/*/*/index.md', 'LICENSE_TEMPLATE.md']

# Infrastructure and tooling
infra:
  - changed-files:
    - any-glob-to-any-file: [
      # Build files
      'src/build/**',
      '.editorconfig', 'mkdocs.yml', '.browserlistrc', 'mlc_config.json',
      '.github/*', 'commitlint*', '*lint*', 'husky*', '.releaserc*', 
      '_typos.toml', '.pre-commit*', '.sourcery.yaml', 'tsconfig*.json',
      'ruff.toml', 'lerna.json'
    ]

deps:
  - changed-files:
    - any-glob-to-any-file: [
      'package.json', 'pyproject.toml', '*-lock.json', '*.lock',
      'requirements*', '**/.uv/**', 'uv.lock', '.python-version', 'bun.lockb'
    ]

script:
  - changed-files:
    - any-glob-to-all-files: ['*.js', '*.ts', '*scripts/**', '*.sh', 'overrides/hooks/**', '*.py', '*.mjs']

style:
  - changed-files:
    - any-glob-to-any-file: ['overrides/**', 'src/assets/**']
    - any-globs-to-all-files: ['!*.js', '!*.ts', '!*.sh', '!*.py', '!*.mjs', '!*.md']

# Repository metadata
repo:
  - changed-files:
    - any-glob-to-any-file: ['README.md', 'CONTRIBUTING.md', '.gitignore', '.gitmodules', 'node_modules/*', '.venv/*', 'UNLICENSE']

