/**
 *! NOTE: The build process generates this file.
 *! DO NOT EDIT THIS FILE DIRECTLY.
 * Edit the build script instead (src/build/config/index.ts).
 *
 * @module data
 * @description A collection of hero videos for the landing page.
 */

export const rawHeroVideos = [
  {
    baseName: "break_free",
    parentPath: "/assets/videos/hero/break_free",
    variants: {
      av1: {
        426: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_426.e31ed2ae.webm",
        640: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_640.6afd59c1.webm",
        854: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_854.f56246c1.webm",
        1280: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_1280.571b5098.webm",
        1920: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_1920.c2d87780.webm",
        2560: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_2560.c0c9d918.webm",
        3840: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_3840.69d07575.webm",
      },
      vp9: {
        426: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_426.3b1e1444.webm",
        640: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_640.50ffc349.webm",
        854: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_854.0b4e678a.webm",
        1280: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_1280.741aa2bd.webm",
        1920: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_1920.5051f4f9.webm",
        2560: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_2560.1647e51d.webm",
        3840: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_3840.df90af50.webm",
      },
      h264: {
        426: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_h264_426.42e89451.mp4",
        640: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_h264_640.1cb2c3ef.mp4",
        854: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_h264_854.c144cbb7.mp4",
        1280: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_h264_1280.df6cfa2a.mp4",
        1920: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_h264_1920.c6fe0649.mp4",
        2560: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_h264_2560.fbfef151.mp4",
        3840: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_h264_3840.2bdbbf19.mp4",
      },
    },
    poster: {
      avif: {
        widths: {
          426: "assets/videos/hero/break_free/posters/break_free_426.15b2f8c2.avif",
          640: "assets/videos/hero/break_free/posters/break_free_640.1f09127c.avif",
          854: "assets/videos/hero/break_free/posters/break_free_854.719c1f80.avif",
          1280: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1280.883f0f57.avif",
          1920: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.a2f4dafc.avif",
          2560: "assets/videos/hero/break_free/posters/break_free_2560.b3be2865.avif",
          3840: "assets/videos/hero/break_free/posters/break_free_3840.5b016e9b.avif",
        },
        srcset:
          "assets/videos/hero/break_free/posters/break_free_3840.5b016e9b.avif 3840w, assets/videos/hero/break_free/posters/break_free_2560.b3be2865.avif 2560w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.a2f4dafc.avif 1920w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1280.883f0f57.avif 1280w, assets/videos/hero/break_free/posters/break_free_854.719c1f80.avif 854w, assets/videos/hero/break_free/posters/break_free_640.1f09127c.avif 640w, assets/videos/hero/break_free/posters/break_free_426.15b2f8c2.avif 426w",
      },
      webp: {
        widths: {
          426: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.435dffdc.webp",
          640: "assets/videos/hero/break_free/posters/break_free_640.23b208a2.webp",
          854: "assets/videos/hero/break_free/posters/break_free_854.ca68c60c.webp",
          1280: "assets/videos/hero/break_free/posters/break_free_1280.2e7a920c.webp",
          1920: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.e4d59947.webp",
          2560: "assets/videos/hero/break_free/posters/break_free_2560.923f39c9.webp",
          3840: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.f21c2a42.webp",
        },
        srcset:
          "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.f21c2a42.webp 3840w, assets/videos/hero/break_free/posters/break_free_2560.923f39c9.webp 2560w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.e4d59947.webp 1920w, assets/videos/hero/break_free/posters/break_free_1280.2e7a920c.webp 1280w, assets/videos/hero/break_free/posters/break_free_854.ca68c60c.webp 854w, assets/videos/hero/break_free/posters/break_free_640.23b208a2.webp 640w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.435dffdc.webp 426w",
      },
      png: {
        widths: {
          426: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.9e78d813.png",
          640: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_640.19194ff4.png",
          854: "assets/videos/hero/break_free/posters/break_free_854.56f0053a.png",
          1280: "assets/videos/hero/break_free/posters/break_free_1280.6088c494.png",
          1920: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.1feeb1dd.png",
          2560: "assets/videos/hero/break_free/posters/break_free_2560.aac4a3cc.png",
          3840: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.bc9c8fe8.png",
        },
        srcset:
          "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.bc9c8fe8.png 3840w, assets/videos/hero/break_free/posters/break_free_2560.aac4a3cc.png 2560w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.1feeb1dd.png 1920w, assets/videos/hero/break_free/posters/break_free_1280.6088c494.png 1280w, assets/videos/hero/break_free/posters/break_free_854.56f0053a.png 854w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_640.19194ff4.png 640w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.9e78d813.png 426w",
      },
    },
    message: "Understanding shouldn't require a degree.",
  },
  {
    baseName: "tokyo_shuffle",
    parentPath: "/assets/videos/hero/tokyo_shuffle",
    variants: {
      av1: {
        426: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_426.e31ed2ae.webm",
        640: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_640.6afd59c1.webm",
        854: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_854.f56246c1.webm",
        1280: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_1280.571b5098.webm",
        1920: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_1920.c2d87780.webm",
        2560: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_2560.c0c9d918.webm",
        3840: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_3840.69d07575.webm",
      },
      vp9: {
        426: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_426.3b1e1444.webm",
        640: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_640.50ffc349.webm",
        854: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_854.0b4e678a.webm",
        1280: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_1280.741aa2bd.webm",
        1920: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_1920.5051f4f9.webm",
        2560: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_2560.1647e51d.webm",
        3840: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_3840.df90af50.webm",
      },
      h264: {
        426: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_h264_426.42e89451.mp4",
        640: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_h264_640.1cb2c3ef.mp4",
        854: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_h264_854.c144cbb7.mp4",
        1280: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_h264_1280.df6cfa2a.mp4",
        1920: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_h264_1920.c6fe0649.mp4",
        2560: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_h264_2560.fbfef151.mp4",
        3840: "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_h264_3840.2bdbbf19.mp4",
      },
    },
    poster: {
      avif: {
        widths: {
          426: "assets/videos/hero/break_free/posters/break_free_426.15b2f8c2.avif",
          640: "assets/videos/hero/break_free/posters/break_free_640.1f09127c.avif",
          854: "assets/videos/hero/break_free/posters/break_free_854.719c1f80.avif",
          1280: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1280.883f0f57.avif",
          1920: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.a2f4dafc.avif",
          2560: "assets/videos/hero/break_free/posters/break_free_2560.b3be2865.avif",
          3840: "assets/videos/hero/break_free/posters/break_free_3840.5b016e9b.avif",
        },
        srcset:
          "assets/videos/hero/break_free/posters/break_free_3840.5b016e9b.avif 3840w, assets/videos/hero/break_free/posters/break_free_2560.b3be2865.avif 2560w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.a2f4dafc.avif 1920w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1280.883f0f57.avif 1280w, assets/videos/hero/break_free/posters/break_free_854.719c1f80.avif 854w, assets/videos/hero/break_free/posters/break_free_640.1f09127c.avif 640w, assets/videos/hero/break_free/posters/break_free_426.15b2f8c2.avif 426w",
      },
      webp: {
        widths: {
          426: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.435dffdc.webp",
          640: "assets/videos/hero/break_free/posters/break_free_640.23b208a2.webp",
          854: "assets/videos/hero/break_free/posters/break_free_854.ca68c60c.webp",
          1280: "assets/videos/hero/break_free/posters/break_free_1280.2e7a920c.webp",
          1920: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.e4d59947.webp",
          2560: "assets/videos/hero/break_free/posters/break_free_2560.923f39c9.webp",
          3840: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.f21c2a42.webp",
        },
        srcset:
          "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.f21c2a42.webp 3840w, assets/videos/hero/break_free/posters/break_free_2560.923f39c9.webp 2560w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.e4d59947.webp 1920w, assets/videos/hero/break_free/posters/break_free_1280.2e7a920c.webp 1280w, assets/videos/hero/break_free/posters/break_free_854.ca68c60c.webp 854w, assets/videos/hero/break_free/posters/break_free_640.23b208a2.webp 640w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.435dffdc.webp 426w",
      },
      png: {
        widths: {
          426: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.9e78d813.png",
          640: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_640.19194ff4.png",
          854: "assets/videos/hero/break_free/posters/break_free_854.56f0053a.png",
          1280: "assets/videos/hero/break_free/posters/break_free_1280.6088c494.png",
          1920: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.1feeb1dd.png",
          2560: "assets/videos/hero/break_free/posters/break_free_2560.aac4a3cc.png",
          3840: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.bc9c8fe8.png",
        },
        srcset:
          "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.bc9c8fe8.png 3840w, assets/videos/hero/break_free/posters/break_free_2560.aac4a3cc.png 2560w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.1feeb1dd.png 1920w, assets/videos/hero/break_free/posters/break_free_1280.6088c494.png 1280w, assets/videos/hero/break_free/posters/break_free_854.56f0053a.png 854w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_640.19194ff4.png 640w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.9e78d813.png 426w",
      },
    },
    message: "Stop the Nonsense",
  },
] as const

export enum HeroName {
  BREAK_FREE = "break_free",
  TOKYO_SHUFFLE = "tokyo_shuffle",
}

export const backupImage = {
  avif: {
    widths: {
      426: "assets/videos/hero/break_free/posters/break_free_426.15b2f8c2.avif",
      640: "assets/videos/hero/break_free/posters/break_free_640.1f09127c.avif",
      854: "assets/videos/hero/break_free/posters/break_free_854.719c1f80.avif",
      1280: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1280.883f0f57.avif",
      1920: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.a2f4dafc.avif",
      2560: "assets/videos/hero/break_free/posters/break_free_2560.b3be2865.avif",
      3840: "assets/videos/hero/break_free/posters/break_free_3840.5b016e9b.avif",
    },
    srcset:
      "assets/videos/hero/break_free/posters/break_free_3840.5b016e9b.avif 3840w, assets/videos/hero/break_free/posters/break_free_2560.b3be2865.avif 2560w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.a2f4dafc.avif 1920w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1280.883f0f57.avif 1280w, assets/videos/hero/break_free/posters/break_free_854.719c1f80.avif 854w, assets/videos/hero/break_free/posters/break_free_640.1f09127c.avif 640w, assets/videos/hero/break_free/posters/break_free_426.15b2f8c2.avif 426w",
  },
  webp: {
    widths: {
      426: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.435dffdc.webp",
      640: "assets/videos/hero/break_free/posters/break_free_640.23b208a2.webp",
      854: "assets/videos/hero/break_free/posters/break_free_854.ca68c60c.webp",
      1280: "assets/videos/hero/break_free/posters/break_free_1280.2e7a920c.webp",
      1920: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.e4d59947.webp",
      2560: "assets/videos/hero/break_free/posters/break_free_2560.923f39c9.webp",
      3840: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.f21c2a42.webp",
    },
    srcset:
      "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.f21c2a42.webp 3840w, assets/videos/hero/break_free/posters/break_free_2560.923f39c9.webp 2560w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.e4d59947.webp 1920w, assets/videos/hero/break_free/posters/break_free_1280.2e7a920c.webp 1280w, assets/videos/hero/break_free/posters/break_free_854.ca68c60c.webp 854w, assets/videos/hero/break_free/posters/break_free_640.23b208a2.webp 640w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.435dffdc.webp 426w",
  },
  png: {
    widths: {
      426: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.9e78d813.png",
      640: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_640.19194ff4.png",
      854: "assets/videos/hero/break_free/posters/break_free_854.56f0053a.png",
      1280: "assets/videos/hero/break_free/posters/break_free_1280.6088c494.png",
      1920: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.1feeb1dd.png",
      2560: "assets/videos/hero/break_free/posters/break_free_2560.aac4a3cc.png",
      3840: "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.bc9c8fe8.png",
    },
    srcset:
      "assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.bc9c8fe8.png 3840w, assets/videos/hero/break_free/posters/break_free_2560.aac4a3cc.png 2560w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.1feeb1dd.png 1920w, assets/videos/hero/break_free/posters/break_free_1280.6088c494.png 1280w, assets/videos/hero/break_free/posters/break_free_854.56f0053a.png 854w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_640.19194ff4.png 640w, assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.9e78d813.png 426w",
  },
} as const
