
/**
 *! NOTE: The build process generates this file.
 *! DO NOT EDIT THIS FILE DIRECTLY.
 * Edit the build script instead (src/build/index.ts).
 *
 * @module data
 * @description A collection of hero videos for the landing page.
 */

export const rawHeroVideos = [
  {
    "baseName": "break_free",
    "parent": "src/assets/videos/hero/break_free",
    "variants": {
      "av1": {
        "426": "",
        "640": "",
        "854": "",
        "1280": "",
        "1920": "",
        "2560": "",
        "3840": ""
      },
      "vp9": {
        "426": "",
        "640": "",
        "854": "",
        "1280": "",
        "1920": "",
        "2560": "",
        "3840": ""
      },
      "h264": {
        "426": "",
        "640": "",
        "854": "",
        "1280": "",
        "1920": "",
        "2560": "",
        "3840": ""
      }
    },
    "poster": {
      "imageName": "",
      "parent": "",
      "images": {}
    }
  },
  {
    "baseName": "tokyo_shuffle",
    "parent": "src/assets/videos/hero/tokyo_shuffle",
    "variants": {
      "av1": {
        "426": "",
        "640": "",
        "854": "",
        "1280": "",
        "1920": "",
        "2560": "",
        "3840": ""
      },
      "vp9": {
        "426": "",
        "640": "",
        "854": "",
        "1280": "",
        "1920": "",
        "2560": "",
        "3840": ""
      },
      "h264": {
        "426": "",
        "640": "",
        "854": "",
        "1280": "",
        "1920": "",
        "2560": "",
        "3840": ""
      }
    },
    "poster": {
      "imageName": "",
      "parent": "",
      "images": {}
    }
  }
] as const;

export enum HeroName {
    Break_free = "BREAK_FREE",
    Tokyo_shuffle = "TOKYO_SHUFFLE"
    }

export backupImage = "[object Object]";

