
/**
 *! NOTE: The build process generates this file.
 *! DO NOT EDIT THIS FILE DIRECTLY.
 * Edit the build script instead (/build/config/index.ts).
 *
 * @module data
 * @description A collection of hero videos for the landing page.
 */

export const rawHeroVideos = [
  {
    baseName: "",
    parent: "",
    variants: {
      av1: {
        426: "/assets/videos/hero/break_free/break_free_av1_426.68b4fcb9.webm",
        640: "docs/assets/videos/hero/break_free/break_free_av1_640.fbba63e1.webm",
        854: "docs/assets/videos/hero/break_free/break_free_av1_854.5653b4a3.webm",
        1280: "docs/assets/videos/hero/break_free/break_free_av1_1280.5924100d.webm",
        1920: "docs/assets/videos/hero/break_free/break_free_av1_1920.15cf893c.webm",
        2560: "docs/assets/videos/hero/break_free/break_free_av1_2560.422dd3aa.webm",
        3840: "docs/assets/videos/hero/break_free/break_free_av1_3840.3f4ab485.webm"
      },
      vp9: {
        426: "docs/assets/videos/hero/break_free/break_free_vp9_426.57d668a7.webm",
        640: "docs/assets/videos/hero/break_free/break_free_vp9_640.a130f758.webm",
        854: "docs/assets/videos/hero/break_free/break_free_vp9_854.47d4071d.webm",
        1280: "docs/assets/videos/hero/break_free/break_free_vp9_1280.5050faa9.webm",
        1920: "docs/assets/videos/hero/break_free/break_free_vp9_1920.1c78a676.webm",
        2560: "docs/assets/videos/hero/break_free/break_free_vp9_2560.8fecc28d.webm",
        3840: "docs/assets/videos/hero/break_free/break_free_vp9_3840.8c366fd1.webm"
      },
      h264: {
        426: "docs/assets/videos/hero/break_free/break_free_h264_426.03ae5a02.mp4",
        640: "docs/assets/videos/hero/break_free/break_free_h264_640.abc514ef.mp4",
        854: "docs/assets/videos/hero/break_free/break_free_h264_854.bd603a43.mp4",
        1280: "docs/assets/videos/hero/break_free/break_free_h264_1280.36973c5d.mp4",
        1920: "docs/assets/videos/hero/break_free/break_free_h264_1920.6fe1c5f9.mp4",
        2560: "docs/assets/videos/hero/break_free/break_free_h264_2560.9a7d9d68.mp4",
        3840: "docs/assets/videos/hero/break_free/break_free_h264_3840.e6f18669.mp4"
      }
    },
    poster: {
      parent: "",
      imageName: "",
      images: {
        avif: {
          widths: {
            426: "docs/assets/videos/hero/break_free/posters/break_free_426.15b2f8c2.avif",
            640: "docs/assets/videos/hero/break_free/posters/break_free_640.1f09127c.avif",
            854: "docs/assets/videos/hero/break_free/posters/break_free_854.719c1f80.avif",
            1280: "docs/assets/videos/hero/break_free/posters/break_free_1280.a70cced8.avif",
            1920: "docs/assets/videos/hero/break_free/posters/break_free_1920.f4ca50fc.avif",
            2560: "docs/assets/videos/hero/break_free/posters/break_free_2560.b3be2865.avif",
            3840: "docs/assets/videos/hero/break_free/posters/break_free_3840.5b016e9b.avif"
          },
          srcset: "docs/assets/videos/hero/break_free/posters/break_free_426.15b2f8c2.avif 426w, docs/assets/videos/hero/break_free/posters/break_free_640.1f09127c.avif 640w, docs/assets/videos/hero/break_free/posters/break_free_854.719c1f80.avif 854w, docs/assets/videos/hero/break_free/posters/break_free_1280.a70cced8.avif 1280w, docs/assets/videos/hero/break_free/posters/break_free_1920.f4ca50fc.avif 1920w, docs/assets/videos/hero/break_free/posters/break_free_2560.b3be2865.avif 2560w, docs/assets/videos/hero/break_free/posters/break_free_3840.5b016e9b.avif 3840w"
        },
        webp: {
          widths: {
            426: "docs/assets/videos/hero/break_free/posters/break_free_426.e5d3453e.webp",
            640: "docs/assets/videos/hero/break_free/posters/break_free_640.23b208a2.webp",
            854: "docs/assets/videos/hero/break_free/posters/break_free_854.ca68c60c.webp",
            1280: "docs/assets/videos/hero/break_free/posters/break_free_1280.2e7a920c.webp",
            1920: "docs/assets/videos/hero/break_free/posters/break_free_1920.822fae28.webp",
            2560: "docs/assets/videos/hero/break_free/posters/break_free_2560.923f39c9.webp",
            3840: "docs/assets/videos/hero/break_free/posters/break_free_3840.a4a844c0.webp"
          },
          srcset: "docs/assets/videos/hero/break_free/posters/break_free_426.e5d3453e.webp 426w, docs/assets/videos/hero/break_free/posters/break_free_640.23b208a2.webp 640w, docs/assets/videos/hero/break_free/posters/break_free_854.ca68c60c.webp 854w, docs/assets/videos/hero/break_free/posters/break_free_1280.2e7a920c.webp 1280w, docs/assets/videos/hero/break_free/posters/break_free_1920.822fae28.webp 1920w, docs/assets/videos/hero/break_free/posters/break_free_2560.923f39c9.webp 2560w, docs/assets/videos/hero/break_free/posters/break_free_3840.a4a844c0.webp 3840w"
        },
        png: {
          widths: {
            426: "docs/assets/videos/hero/break_free/posters/break_free_426.34c4c513.png",
            640: "docs/assets/videos/hero/break_free/posters/break_free_640.2cbe3fc9.png",
            854: "docs/assets/videos/hero/break_free/posters/break_free_854.56f0053a.png",
            1280: "docs/assets/videos/hero/break_free/posters/break_free_1280.6088c494.png",
            1920: "docs/assets/videos/hero/break_free/posters/break_free_1920.e29d593a.png",
            2560: "docs/assets/videos/hero/break_free/posters/break_free_2560.aac4a3cc.png",
            3840: "docs/assets/videos/hero/break_free/posters/break_free_3840.c12169da.png"
          },
          srcset: "docs/assets/videos/hero/break_free/posters/break_free_426.34c4c513.png 426w, docs/assets/videos/hero/break_free/posters/break_free_640.2cbe3fc9.png 640w, docs/assets/videos/hero/break_free/posters/break_free_854.56f0053a.png 854w, docs/assets/videos/hero/break_free/posters/break_free_1280.6088c494.png 1280w, docs/assets/videos/hero/break_free/posters/break_free_1920.e29d593a.png 1920w, docs/assets/videos/hero/break_free/posters/break_free_2560.aac4a3cc.png 2560w, docs/assets/videos/hero/break_free/posters/break_free_3840.c12169da.png 3840w"
        }
      }
    }
  },
  {
    baseName: "",
    parent: "",
    variants: {
      av1: {
        426: "docs/assets/videos/hero/break_free/break_free_av1_426.68b4fcb9.webm",
        640: "docs/assets/videos/hero/break_free/break_free_av1_640.fbba63e1.webm",
        854: "docs/assets/videos/hero/break_free/break_free_av1_854.5653b4a3.webm",
        1280: "docs/assets/videos/hero/break_free/break_free_av1_1280.5924100d.webm",
        1920: "docs/assets/videos/hero/break_free/break_free_av1_1920.15cf893c.webm",
        2560: "docs/assets/videos/hero/break_free/break_free_av1_2560.422dd3aa.webm",
        3840: "docs/assets/videos/hero/break_free/break_free_av1_3840.3f4ab485.webm"
      },
      vp9: {
        426: "docs/assets/videos/hero/break_free/break_free_vp9_426.57d668a7.webm",
        640: "docs/assets/videos/hero/break_free/break_free_vp9_640.a130f758.webm",
        854: "docs/assets/videos/hero/break_free/break_free_vp9_854.47d4071d.webm",
        1280: "docs/assets/videos/hero/break_free/break_free_vp9_1280.5050faa9.webm",
        1920: "docs/assets/videos/hero/break_free/break_free_vp9_1920.1c78a676.webm",
        2560: "docs/assets/videos/hero/break_free/break_free_vp9_2560.8fecc28d.webm",
        3840: "docs/assets/videos/hero/break_free/break_free_vp9_3840.8c366fd1.webm"
      },
      h264: {
        426: "docs/assets/videos/hero/break_free/break_free_h264_426.03ae5a02.mp4",
        640: "docs/assets/videos/hero/break_free/break_free_h264_640.abc514ef.mp4",
        854: "docs/assets/videos/hero/break_free/break_free_h264_854.bd603a43.mp4",
        1280: "docs/assets/videos/hero/break_free/break_free_h264_1280.36973c5d.mp4",
        1920: "docs/assets/videos/hero/break_free/break_free_h264_1920.6fe1c5f9.mp4",
        2560: "docs/assets/videos/hero/break_free/break_free_h264_2560.9a7d9d68.mp4",
        3840: "docs/assets/videos/hero/break_free/break_free_h264_3840.e6f18669.mp4"
      }
    },
    poster: {
      parent: "",
      imageName: "",
      images: {
        avif: {
          widths: {
            426: "docs/assets/videos/hero/break_free/posters/break_free_426.15b2f8c2.avif",
            640: "docs/assets/videos/hero/break_free/posters/break_free_640.1f09127c.avif",
            854: "docs/assets/videos/hero/break_free/posters/break_free_854.719c1f80.avif",
            1280: "docs/assets/videos/hero/break_free/posters/break_free_1280.a70cced8.avif",
            1920: "docs/assets/videos/hero/break_free/posters/break_free_1920.f4ca50fc.avif",
            2560: "docs/assets/videos/hero/break_free/posters/break_free_2560.b3be2865.avif",
            3840: "docs/assets/videos/hero/break_free/posters/break_free_3840.5b016e9b.avif"
          },
          srcset: "docs/assets/videos/hero/break_free/posters/break_free_426.15b2f8c2.avif 426w, docs/assets/videos/hero/break_free/posters/break_free_640.1f09127c.avif 640w, docs/assets/videos/hero/break_free/posters/break_free_854.719c1f80.avif 854w, docs/assets/videos/hero/break_free/posters/break_free_1280.a70cced8.avif 1280w, docs/assets/videos/hero/break_free/posters/break_free_1920.f4ca50fc.avif 1920w, docs/assets/videos/hero/break_free/posters/break_free_2560.b3be2865.avif 2560w, docs/assets/videos/hero/break_free/posters/break_free_3840.5b016e9b.avif 3840w"
        },
        webp: {
          widths: {
            426: "docs/assets/videos/hero/break_free/posters/break_free_426.e5d3453e.webp",
            640: "docs/assets/videos/hero/break_free/posters/break_free_640.23b208a2.webp",
            854: "docs/assets/videos/hero/break_free/posters/break_free_854.ca68c60c.webp",
            1280: "docs/assets/videos/hero/break_free/posters/break_free_1280.2e7a920c.webp",
            1920: "docs/assets/videos/hero/break_free/posters/break_free_1920.822fae28.webp",
            2560: "docs/assets/videos/hero/break_free/posters/break_free_2560.923f39c9.webp",
            3840: "docs/assets/videos/hero/break_free/posters/break_free_3840.a4a844c0.webp"
          },
          srcset: "docs/assets/videos/hero/break_free/posters/break_free_426.e5d3453e.webp 426w, docs/assets/videos/hero/break_free/posters/break_free_640.23b208a2.webp 640w, docs/assets/videos/hero/break_free/posters/break_free_854.ca68c60c.webp 854w, docs/assets/videos/hero/break_free/posters/break_free_1280.2e7a920c.webp 1280w, docs/assets/videos/hero/break_free/posters/break_free_1920.822fae28.webp 1920w, docs/assets/videos/hero/break_free/posters/break_free_2560.923f39c9.webp 2560w, docs/assets/videos/hero/break_free/posters/break_free_3840.a4a844c0.webp 3840w"
        },
        png: {
          widths: {
            426: "docs/assets/videos/hero/break_free/posters/break_free_426.34c4c513.png",
            640: "docs/assets/videos/hero/break_free/posters/break_free_640.2cbe3fc9.png",
            854: "docs/assets/videos/hero/break_free/posters/break_free_854.56f0053a.png",
            1280: "docs/assets/videos/hero/break_free/posters/break_free_1280.6088c494.png",
            1920: "docs/assets/videos/hero/break_free/posters/break_free_1920.e29d593a.png",
            2560: "docs/assets/videos/hero/break_free/posters/break_free_2560.aac4a3cc.png",
            3840: "docs/assets/videos/hero/break_free/posters/break_free_3840.c12169da.png"
          },
          srcset: "docs/assets/videos/hero/break_free/posters/break_free_426.34c4c513.png 426w, docs/assets/videos/hero/break_free/posters/break_free_640.2cbe3fc9.png 640w, docs/assets/videos/hero/break_free/posters/break_free_854.56f0053a.png 854w, docs/assets/videos/hero/break_free/posters/break_free_1280.6088c494.png 1280w, docs/assets/videos/hero/break_free/posters/break_free_1920.e29d593a.png 1920w, docs/assets/videos/hero/break_free/posters/break_free_2560.aac4a3cc.png 2560w, docs/assets/videos/hero/break_free/posters/break_free_3840.c12169da.png 3840w"
        }
      }
    }
  }
] as const;

export enum HeroName {
     = "",
     = ""
    }

export const backupImage = {
  parent: "src/assets/images/break_free",
  imageName: "break_free",
  images: {
    avif: {
      widths: {
        426: "docs/assets/videos/hero/break_free/posters/break_free_426.15b2f8c2.avif",
        640: "docs/assets/videos/hero/break_free/posters/break_free_640.1f09127c.avif",
        854: "docs/assets/videos/hero/break_free/posters/break_free_854.719c1f80.avif",
        1280: "docs/assets/videos/hero/break_free/posters/break_free_1280.a70cced8.avif",
        1920: "docs/assets/videos/hero/break_free/posters/break_free_1920.f4ca50fc.avif",
        2560: "docs/assets/videos/hero/break_free/posters/break_free_2560.b3be2865.avif",
        3840: "docs/assets/videos/hero/break_free/posters/break_free_3840.5b016e9b.avif"
      },
      srcset: "docs/assets/videos/hero/break_free/posters/break_free_426.15b2f8c2.avif 426w, docs/assets/videos/hero/break_free/posters/break_free_640.1f09127c.avif 640w, docs/assets/videos/hero/break_free/posters/break_free_854.719c1f80.avif 854w, docs/assets/videos/hero/break_free/posters/break_free_1280.a70cced8.avif 1280w, docs/assets/videos/hero/break_free/posters/break_free_1920.f4ca50fc.avif 1920w, docs/assets/videos/hero/break_free/posters/break_free_2560.b3be2865.avif 2560w, docs/assets/videos/hero/break_free/posters/break_free_3840.5b016e9b.avif 3840w"
    },
    webp: {
      widths: {
        426: "docs/assets/videos/hero/break_free/posters/break_free_426.e5d3453e.webp",
        640: "docs/assets/videos/hero/break_free/posters/break_free_640.23b208a2.webp",
        854: "docs/assets/videos/hero/break_free/posters/break_free_854.ca68c60c.webp",
        1280: "docs/assets/videos/hero/break_free/posters/break_free_1280.2e7a920c.webp",
        1920: "docs/assets/videos/hero/break_free/posters/break_free_1920.822fae28.webp",
        2560: "docs/assets/videos/hero/break_free/posters/break_free_2560.923f39c9.webp",
        3840: "docs/assets/videos/hero/break_free/posters/break_free_3840.a4a844c0.webp"
      },
      srcset: "docs/assets/videos/hero/break_free/posters/break_free_426.e5d3453e.webp 426w, docs/assets/videos/hero/break_free/posters/break_free_640.23b208a2.webp 640w, docs/assets/videos/hero/break_free/posters/break_free_854.ca68c60c.webp 854w, docs/assets/videos/hero/break_free/posters/break_free_1280.2e7a920c.webp 1280w, docs/assets/videos/hero/break_free/posters/break_free_1920.822fae28.webp 1920w, docs/assets/videos/hero/break_free/posters/break_free_2560.923f39c9.webp 2560w, docs/assets/videos/hero/break_free/posters/break_free_3840.a4a844c0.webp 3840w"
    },
    png: {
      widths: {
        426: "docs/assets/videos/hero/break_free/posters/break_free_426.34c4c513.png",
        640: "docs/assets/videos/hero/break_free/posters/break_free_640.2cbe3fc9.png",
        854: "docs/assets/videos/hero/break_free/posters/break_free_854.56f0053a.png",
        1280: "docs/assets/videos/hero/break_free/posters/break_free_1280.6088c494.png",
        1920: "docs/assets/videos/hero/break_free/posters/break_free_1920.e29d593a.png",
        2560: "docs/assets/videos/hero/break_free/posters/break_free_2560.aac4a3cc.png",
        3840: "docs/assets/videos/hero/break_free/posters/break_free_3840.c12169da.png"
      },
      srcset: "docs/assets/videos/hero/break_free/posters/break_free_426.34c4c513.png 426w, docs/assets/videos/hero/break_free/posters/break_free_640.2cbe3fc9.png 640w, docs/assets/videos/hero/break_free/posters/break_free_854.56f0053a.png 854w, docs/assets/videos/hero/break_free/posters/break_free_1280.6088c494.png 1280w, docs/assets/videos/hero/break_free/posters/break_free_1920.e29d593a.png 1920w, docs/assets/videos/hero/break_free/posters/break_free_2560.aac4a3cc.png 2560w, docs/assets/videos/hero/break_free/posters/break_free_3840.c12169da.png 3840w"
    }
  }
} as const;
