export BUN_INSTALL="/home/vscode/.bun"
export bash_completion="$HOME/.local/share/bash-completion/completions"
export RUSTUP_TERM_COLOR=always
export RUSTUP_TOOLCHAIN=stable-x86_64-unknown-linux-gnu
alias rgg='rg --no-ignore --trim --pretty --colors "match:fg:white" --colors "path:fg:blue" --smart-case --search-zip --hidden'
alias rgf='rg --files | rgg'
alias rgc='rgg --count'
alias ll='ls -alFh'
alias llr='ls -alFhR'
alias lld='ls -alFhd'
alias lldr='ls -alFhdR'
alias locate='lolcate'
alias updatedb='lolcate --update'
export PATH="$BUN_INSTALL/bin:$HOME/.cargo/bin:$HOME/bin:$HOME/sbin:$PATH:/opt/bin:/opt/sbin:/opt/local/bin:/opt/local/sbin"
export UV_PYTHON_DOWNLOADS="automatic"
export UV_CACHE_DIR="/workspaces/PlainLicense/.cache/uv"
export UV_COLOR="always"
export UV_PYTHON="cpython-3.13.0-linux-x86_64-gnu"
export UV_PYTHON_PREFERENCE="managed"
export UV_COMPILE_BYTECODE="true"
export PYVENV="/workspaces/PlainLicense/.venv/bin/activate"
export FORCE_COLOR=1
export CLICOLOR_FORCE=1
export FILEHANDLER_ENABLED="true"
export LOG_PATH="$HOME/logs"
SIGNING_KEY="$(ssh-add -L)"
export SIGNING_KEY
