
/**
 *! NOTE: The build process generates this file.
 *! DO NOT EDIT THIS FILE DIRECTLY.
 * Edit the build script instead (src/build/index.ts).
 *
 * @module data
 * @description A collection of hero videos for the landing page.
 */

export const rawHeroVideos = [
  {
    "baseName": "",
    "parent": "",
    "variants": {
      "av1": {
        "426": "assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_426.e31ed2ae.webm",
        "640": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_640.6afd59c1.webm",
        "854": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_854.f56246c1.webm",
        "1280": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_1280.571b5098.webm",
        "1920": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_1920.c2d87780.webm",
        "2560": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_2560.c0c9d918.webm",
        "3840": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_3840.69d07575.webm"
      },
      "vp9": {
        "426": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_426.3b1e1444.webm",
        "640": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_640.50ffc349.webm",
        "854": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_854.0b4e678a.webm",
        "1280": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_1280.741aa2bd.webm",
        "1920": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_1920.5051f4f9.webm",
        "2560": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_2560.1647e51d.webm",
        "3840": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_3840.df90af50.webm"
      },
      "h264": {
        "426": "",
        "640": "",
        "854": "",
        "1280": "",
        "1920": "",
        "2560": "",
        "3840": "",
        "": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_h264_.c144cbb7.mp4"
      }
    },
    "poster": {
      "parent": "",
      "imageName": "",
      "images": {
        "avif": {
          "widths": {
            "426": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.b057edfa.avif",
            "640": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_640.3afec5cd.avif",
            "854": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_854.56629992.avif",
            "1280": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1280.883f0f57.avif",
            "1920": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.a2f4dafc.avif",
            "2560": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_2560.43267f7f.avif",
            "3840": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.79fba1fc.avif"
          },
          "srcset": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.b057edfa.avif 426w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_640.3afec5cd.avif 640w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_854.56629992.avif 854w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1280.883f0f57.avif 1280w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.a2f4dafc.avif 1920w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_2560.43267f7f.avif 2560w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.79fba1fc.avif 3840w"
        },
        "webp": {
          "widths": {
            "426": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.435dffdc.webp",
            "640": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_640.4f1c6fe6.webp",
            "854": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_854.48926405.webp",
            "1280": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1280.a31d64a3.webp",
            "1920": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.e4d59947.webp",
            "2560": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_2560.df1a4396.webp",
            "3840": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.f21c2a42.webp"
          },
          "srcset": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.435dffdc.webp 426w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_640.4f1c6fe6.webp 640w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_854.48926405.webp 854w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1280.a31d64a3.webp 1280w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.e4d59947.webp 1920w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_2560.df1a4396.webp 2560w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.f21c2a42.webp 3840w"
        },
        "png": {
          "widths": {
            "426": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.9e78d813.png",
            "640": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_640.19194ff4.png",
            "854": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_854.9828900a.png",
            "1280": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1280.e338ecde.png",
            "1920": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.1feeb1dd.png",
            "2560": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_2560.4178e46c.png",
            "3840": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.bc9c8fe8.png"
          },
          "srcset": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.9e78d813.png 426w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_640.19194ff4.png 640w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_854.9828900a.png 854w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1280.e338ecde.png 1280w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.1feeb1dd.png 1920w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_2560.4178e46c.png 2560w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.bc9c8fe8.png 3840w"
        }
      }
    }
  },
  {
    "baseName": "",
    "parent": "",
    "variants": {
      "av1": {
        "426": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_426.e31ed2ae.webm",
        "640": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_640.6afd59c1.webm",
        "854": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_854.f56246c1.webm",
        "1280": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_1280.571b5098.webm",
        "1920": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_1920.c2d87780.webm",
        "2560": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_2560.c0c9d918.webm",
        "3840": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_av1_3840.69d07575.webm"
      },
      "vp9": {
        "426": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_426.3b1e1444.webm",
        "640": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_640.50ffc349.webm",
        "854": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_854.0b4e678a.webm",
        "1280": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_1280.741aa2bd.webm",
        "1920": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_1920.5051f4f9.webm",
        "2560": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_2560.1647e51d.webm",
        "3840": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_vp9_3840.df90af50.webm"
      },
      "h264": {
        "426": "",
        "640": "",
        "854": "",
        "1280": "",
        "1920": "",
        "2560": "",
        "3840": "",
        "": "docs/assets/videos/hero/tokyo_shuffle/tokyo_shuffle_h264_.c144cbb7.mp4"
      }
    },
    "poster": {
      "parent": "",
      "imageName": "",
      "images": {
        "avif": {
          "widths": {
            "426": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.b057edfa.avif",
            "640": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_640.3afec5cd.avif",
            "854": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_854.56629992.avif",
            "1280": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1280.883f0f57.avif",
            "1920": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.a2f4dafc.avif",
            "2560": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_2560.43267f7f.avif",
            "3840": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.79fba1fc.avif"
          },
          "srcset": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.b057edfa.avif 426w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_640.3afec5cd.avif 640w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_854.56629992.avif 854w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1280.883f0f57.avif 1280w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.a2f4dafc.avif 1920w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_2560.43267f7f.avif 2560w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.79fba1fc.avif 3840w"
        },
        "webp": {
          "widths": {
            "426": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.435dffdc.webp",
            "640": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_640.4f1c6fe6.webp",
            "854": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_854.48926405.webp",
            "1280": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1280.a31d64a3.webp",
            "1920": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.e4d59947.webp",
            "2560": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_2560.df1a4396.webp",
            "3840": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.f21c2a42.webp"
          },
          "srcset": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.435dffdc.webp 426w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_640.4f1c6fe6.webp 640w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_854.48926405.webp 854w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1280.a31d64a3.webp 1280w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.e4d59947.webp 1920w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_2560.df1a4396.webp 2560w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.f21c2a42.webp 3840w"
        },
        "png": {
          "widths": {
            "426": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.9e78d813.png",
            "640": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_640.19194ff4.png",
            "854": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_854.9828900a.png",
            "1280": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1280.e338ecde.png",
            "1920": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.1feeb1dd.png",
            "2560": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_2560.4178e46c.png",
            "3840": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.bc9c8fe8.png"
          },
          "srcset": "docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_426.9e78d813.png 426w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_640.19194ff4.png 640w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_854.9828900a.png 854w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1280.e338ecde.png 1280w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_1920.1feeb1dd.png 1920w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_2560.4178e46c.png 2560w, docs/assets/videos/hero/tokyo_shuffle/posters/tokyo_shuffle_3840.bc9c8fe8.png 3840w"
        }
      }
    }
  }
] as const;

export enum HeroName {
     = "",
     = ""
    }

export backupImage = "[object Object]";
