name: Build

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      permissions:
        contents: write
        pull-requests: read
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            submodules: recursive
        - name: Setup Bun
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: latest
        - name: cache
          uses: actions/cache@v4
          with:
            path: |
              ~/.bun/install/cache
            key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
            restore-keys: |
              ${{ runner.os }}-bun-
        - name: install dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          run: |
            bun i -d --peer --optional --no-interactive &&
            export NODE_ENV=production &&
            bun run build

        - name: Configure Git Credentials
          run: |
            git config user.name github-actions[bot]
            git config user.email "action@github.com"
        - name: Commit build
          run: |
            git add --all
            git commit -m "Build site"
            git push
  notify:
      needs: [build]
      if: failure()
      uses: ./.github/workflows/notify.yml
      permissions:
        contents: read
        pull-requests: read
        statuses: write
        issues: write
