name: Combine Dependabot PRs

on:
  schedule:
    - cron: '0 1 * * 5' # Fridays at 01:00
  workflow_dispatch: # allows you to manually trigger the workflow

# The minimum permissions required to run this Action
permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  combine-prs:
    runs-on: ubuntu-latest

    steps:
      - name: combine-prs
        id: combine-prs
        uses: github/combine-prs@v5.2.0
        with:
          labels: deps, bot
          branch_prefix: 'dependabot'
          pr_title: '[Dependabot] Combined Dependency Updates'
          min_combine_number: 3
          ci_required: false
          review_required: false
          github_token: ${{ github.token }}
          autoclose: true
          update_branch: true
          create_from_scratch: true
