name: PR Lint
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pr-check:
    name: PR Lint Checks
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: inspect links
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          fail_on_error: true
      - name: Check spelling in markdown files
        uses: crate-ci/typos@master
        with:
          config: ./_typos.toml
          write_changes: true
      - name: Label PRs
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
      - name: sourcery code review
        uses: sourcery-ai/action@v1
        with:
          token: ${{ secrets.SOURCERY_TOKEN }}
      - name: commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff-index --quiet HEAD || git commit -m "bot(ci): PR lint [ci]"
          git push

  notify:
      needs: [pr-check]
      if: failure()
      uses: ./.github/workflows/notify.yml
      permissions:
        contents: read
        pull-requests: read
        statuses: write
        issues: write
