name: Release
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read
  statuses: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: |
          bun i -d --peer --optional --no-interactive
          bun i --no-interactive -g semantic-release-cli commitlint lerna
          export NODE_ENV=production
      - name: Run Lerna Versioning
        run: npx lerna version --yes --conventional-commits
      - name: Release project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: bunx -b semantic-release
      - name: Commit updated changelogs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git diff-index --quiet HEAD || git commit -m "bot(ci): update changelogs [ci]"
          git push

  notify:
      needs: [release]
      if: failure()
      uses: ./.github/workflows/notify.yml
